swagger: '2.0'
info:
  version: '1.0.0'
  title: 'My Application API'
  description: 'API documentation for My Application'
basePath: '/api'
paths:
  /users:
    post:
      summary: Create a new user
      description: Endpoint to register a new user
      parameters:
        - name: user
          in: body
          description: User object
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
  /users/login:
    post:
      summary: User login
      description: Endpoint for user authentication
      parameters:
        - name: credentials
          in: body
          description: User credentials
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: User authenticated successfully
        '401':
          description: Unauthorized
