swagger: '2.0'
info:
  version: '1.0.0'
  title: Sample Post API
  description: CRUD operations for managing posts
basePath: /api
tags:
  - name: Posts
    description: Operations related to posts
paths:
  /posts:
    post:
      tags:
        - Posts
      summary: Create a new post
      parameters:
        - name: body
          in: body
          description: Post object
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Post'
  /posts/{postId}:
    get:
      tags:
        - Posts
      summary: Get a post by ID
      parameters:
        - name: postId
          in: path
          description: ID of the post to retrieve
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
    put:
      tags:
        - Posts
      summary: Update a post by ID
      parameters:
        - name: postId
          in: path
          description: ID of the post to update
          required: true
          type: string
        - name: body
          in: body
          description: Updated post object
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
    delete:
      tags:
        - Posts
      summary: Delete a post by ID
      parameters:
        - name: postId
          in: path
          description: ID of the post to delete
          required: true
          type: string
      responses:
        '200':
          description: OK
definitions:
  Post:
    type: object
    properties:
      _id:
        type: string
      title:
        type: string
      body:
        type: string
      author:
        type: string
      authorId:
        type: string
      lastModification:
        type: string
        format: date-time
      __v:
        type: integer

